### ISSUE TITLE
Change gump ID's?

### ISSUE THREAD

**Issue by fmikker** [her/uosteam#10]
Hi and thank you for sharing all these scripts!

I need to change the gump-id's, such as the one for Blacksmithy below, where can I get the id for gump `0x432d1ae9`for example?
The gump has a different ID on the shard I'm playing on, so I would like to change a lot of them.
```
  if usetype 0xfbb 'any' 'backpack'
    waitforgump 0x432d1ae9 15000
    sysmsg 'poo'
    replygump 0x432d1ae9 50
    waitforgump 0x432d1ae9 15000
    replygump 0x432d1ae9 16
    pause 2000
  endif
```
Thanks

**Comment by fleekix** [comment]
Just clone the repo and do it

**Comment by fmikker** [comment]
> Just clone the repo and do it
> […](#)

Yeah, but I don't know where to get the ID's from. The Object Inspector in UOS can't inspect gumps. If I knew that I'd already been sed'ing away.

**Comment by her** [comment]
>sed'ing away 

_nice_.

@fmikker you want to record the interaction in UOS and when you select a gump it should store that value which you can then use your favorite tool to replace based on match :)

**Comment by fmikker** [comment]
> > sed'ing away
> 
> _nice_.
> 
> @fmikker you want to record the interaction in UOS and when you select a gump it should store that value which you can then use your favorite tool to replace based on match :)

Yeah I've tried that, but the only thing that sticks in the code window in UOS when recording while I'm crafting a Plate Gorget is the following:
```
useobject 0x432d1b2d
waitfortarget 15000
target! 0x433305f5
```
I am clearly doing something wrong..

**Comment by her** [comment]
`useobject 0x432d1b2d` -> hammer/tongs? 
`target! 0x433305f5` -> menu item, i.e. gorget? 

When you select your item from the crafting menu do you not get a `waitforgump <gumpid>` ? 

Feel free to post some screenshots, that may help us out :)

**Comment by fmikker** [comment]
> `useobject 0x432d1b2d` -> hammer/tongs?

Yes BS Hammer

> `target! 0x433305f5` -> menu item, i.e. gorget?
Yes

> 
> When you select your item from the crafting menu do you not get a `waitforgump <gumpid>` ?

Nope, the only thing that pops in the macro textarea is the three lines that I posted earlier.

> 
> Feel free to post some screenshots, that may help us out :)

I'm running the UOS client in Windows 10 with Win7 compability mode as administrator, and I don't think any screenshot will be helpful at this point :)

**Comment by fmikker** [comment]
Just tried to reproduce the issue in Windows 7, and the result is the same. :( The macro textbox is only populated with the following code:
```
useobject 0x432d1b2d
waitfortarget 15000
target! 0x433305f5
```

**Comment by fleekix** [comment]
Which object are you double clicking on?

**Comment by fleekix** [comment]
Sorry for butting in here, I notice the macro output is for dclicking a thing and then targetting something. That is what will generate if say I dclick my scissors and then target something.

useobject 0x41e6600e
waitfortarget 15000
target! 0x68d25

That is the output for that type of action, but if you click anything that gives you a menu like a runebook or crafting tool it should open a gump and give you its ID. Try other tools like a sewing kit or whatever else and see if that doesn't give the correct output.
By the way what server are you playing on? you may need to update your client perhaps

**Comment by her** [comment]
@fleekix not butting in at all! Thank you for helping out, you rock!

**Comment by her** [comment]
@fmikker Any luck?

**Comment by fmikker** [comment]
@fleekix 
>  That is the output for that type of action, but if you click anything that gives you a menu like a 
> runebook or crafting tool it should open a gump and give you its ID.

Yes, it should. But it doesn't and that's the issue I'm facing.
I'm playing on Zuluhotel Omega.

To take a new very simple problem description with my ranger below:

Steps to reproduce:
* Stand beside a oven
* Press "Record" in UOS
* Double-click Fishsteak
* Await the gump
* Select "10 Fishsteaks"
* Cooking starting

What I expected to see:
Input in the macro window registering that a gump has been raised and the gump ID is saved to the macro window.

What I saw instead:
No gump is registered in the macro window, and only the object Raw Fishsteaks are saved to the window with the following single line of code:
```
useobject 0x43913b58
```
UOS Version: 1.0.5
Ultima Online: Installed from scratch via the installer setup-1.46.0.3.exe
Zuluhotelomega.exe version 1.0 (The latest and only shard files installer)

This problem has been verified on Windows 7 and Windows 10, running as administrator, both with compatible mode for windows 7 on and off.

Any hints would be helpful, 
cheers

**Comment by fleekix** [comment]
That’s really odd. I’m not familiar with that server but just for troubleshooting I would try both if the following. 
1. Update your client (just run the built in osi updater) 
2. Create an account on another server and attempt the same thing in UOS
This would hopefully isolate the issue to your server or your specific pc and install

**Comment by fmikker** [comment]
@fleekix @her 
Thanks for all the pointers, but it seems like I can't get UOS to work on the shard I'm playing, so I'm falling back to EasyUO and Razor which I'm familiar with.

Again, thank you! 

P.S Join https://zuluhotelomega.com/ if you want to and say hello :) My ingame nick is Sockerconny.
Cheers
