### ISSUE TITLE
TreasureSort head message (probably out of range)

### ISSUE THREAD

**Issue by cccsss01** [her/uosteam#12]
I continually get stopping, i'm going to change 'chest' '2' and see if that works, however the script keeps stopping.

**Comment by her** [comment]
@cccsss01 did this end up fixing your issue?

**Comment by cccsss01** [comment]
I think that worked, also, i'd like to let you know, i think the script stops with unrecognized items, i haven't tested/added them yet, but shepherds crook and skinning knife i believe.

**Comment by cccsss01** [comment]
I run i multiple times and it works.

**Comment by her** [comment]
@cccsss01 Excellent! Glad it worked out. 

Feel free to post your code here too, maybe someone else will find it helpful in the future.

**Comment by cccsss01** [comment]
Unfortunately my edits don't work.  When i use object inspector, it doesn't
appear to be the same types of code.  Do you know where I can learn about
it?  Possibly the code for @graphictype or objectype or something?
