### ISSUE TITLE
about a script (Necromancer Trainer)

### ISSUE THREAD

**Issue by vertex101** [her/uosteam#4]
i was wondering if there was one out there for necro training as i dont see one in any of the folders

**Comment by her** [comment]
Thanks for the inquiry @vertex101 

It doesn't appear we have a script right now in the library that does this (as you observed) 

I personally do not play on a server that has a Necromancer, so it would be challenging for me to write one. Do you feel like taking a stab at making one? 

I'm going to leave this issue open for further discussion. This would be a great first issue for someone who'd like to make a contribution to the script library! 

PS If you happen to know where one is, please make a PR or just point me at it and I'll bring in the fold 👍

**Comment by vertex101** [comment]
sorry for the late response work been keeping me busy but i can try to make a script for it i really havent done any script making like this :P

**Comment by her** [comment]
No worries my reply was a bit late too 😅 and for the same reasons (work!)

I think you can do it! There's some documentation here on the syntax: https://github.com/her/uosteam/blob/master/uos/UOSteamDocumentation.pdf 

If you get stuck feel free to post what you've got here and myself or anyone watching can maybe chime in and make some suggestions to get you unblocked.

**Comment by her** [comment]
https://github.com/her/uosteam/pull/5 

Merged 🙂

**Comment by vertex101** [comment]
idk if it fully works or not since the character i had loaded up is already GM necro haha

**Comment by her** [comment]
I think there is the case where maybe a script doesn't work perfectly or comes very close to what someone needs and in that case hopefully we get a friendly PR or issue made so we're made aware and can enhance if needed 😄 

Thanks for the great contribution @vertex101 !
